### ISSUE TITLE
[Feature] Send TimeSwitch to system tray when closing the app with active timer

### ISSUE THREAD

**Issue by hyuri** [fsobolev/timeswitch#36]
Hey!

What do you think of sending the app to the system tray after we start a timer and close the app, so that it gives visual confirmation that a timer is running? Similar to when we set an alarm on mobile phones and an alarm clock icon shows up in the top bar so we are aware that an alarm is set.

This system tray menu could even contain some labels and options such as:
- A label containing Action type of the active timer + time remaining countdown (examples: "Power off in 5:37"; "Run Command in 0:23"; "Notification in 1:45")
- An option to stop/cancel the timer

And the app could stay there in the system tray until the timer rings or when we press "Stop". Then it disappears from the system tray.

**Comment by fsobolev** [comment]
> Similar to when we set an alarm on mobile phones and an alarm clock icon shows up in the top bar so we are aware that a an alarm is set.

To implement something like this it requires to have [background portal UI in GNOME Shell](https://gitlab.gnome.org/Teams/Design/os-mockups/-/issues/191), which I'm really looking forward to. As soon as it will appear, I will definitely make Time Switch use it.

But until then, I can see 2 possible ways to implement what you ask for:
1. Shell extension. I have no experience in writing extensions and I don't know what should be implemented in Time Switch to sync with a companion extension. If anybody would work on that, I would be happy to add such feature. But currently I'm not motivated to study all stuff that is required to only implement that. Maybe sometime... But not in the near future.
2. Classic system tray (appindicator). This is what I will not accept even if somebody will implement it somehow. This is not supported in GNOME Shell out of the box - and I'm glad it is. I share an opinion that traditional desktop system tray is an old concept that should be left in the past. And it is a huge annoyance that there is no proper replacement for it yet. But I don't find it reasonable to stick with something old and inconvenient. So this is no go.

Time Switch doesn't hide anywhere automatically, you can minimize it or move to another workspace and see from overview pretty quickly that it's running and how much time is left. I totally understand it's not what you asked for - but this is a way to use the app that GNOME and basically any other DE provides you.

I will close this issue as not planned. Not because this feature will never be implemented, but because I don't find a way to implement it for now, and I don't want this issue to be a marker of an ongoing process of implementing classic system tray icon for the app.

**Comment by hyuri** [comment]
Understood. Let's hope the background portal gets implemented.

Thanks!

**Comment by fsobolev** [comment]
https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/2624

Let's pray this will be merged soon and shipped in the next GNOME release. I will then reopen this issue.

**Comment by hyuri** [comment]
🤞

**Comment by fsobolev** [comment]
I just updated to GNOME 44 Beta, and as expected Time Switch is shown in background apps.

![](https://user-images.githubusercontent.com/117388856/224075500-a510c3e6-cbe3-49a0-a3a8-d7d49c5b6c45.png)

I know it's possible to set status string there that can be used to show action and time, so I'm reopening this issue until I implement this status string. Unfortunately I'm very inactive recently, but I will try to find time for this before GNOME 44 release (March 22).

Take note that this works only for Flatpak version of the app, I can't to anything with this, that's how background portal works.

**Comment by fsobolev** [comment]
![Снимок экрана от 2023-03-17 18-24-03](https://user-images.githubusercontent.com/117388856/225959196-f041b5fa-a553-48a7-9f8e-ada1aa2151c3.png)
