### ISSUE TITLE
bash commands execute on a timer

### ISSUE THREAD

**Issue by amikha1lov** [fsobolev/timeswitch#4]
Hi. thanks for the great app. Is it possible in the future to make arbitrary bash commands execute on a timer?

**Comment by fsobolev** [comment]
Initially I decided to not implement this feature for 2 reasons:
* It's potentially unsafe, because such commands must be executed outside of flatpak sandbox;
* Having an app to type commands into instead of opening a terminal and typing the same but prepended by `sleep N &&` seems pointless.

I see users who avoid terminal and such things as main target userbase. So possibility to just type and execute command on timer is against my vision of the app. Users who are familiar with a terminal can do all the things the app does pretty easily (`sleep $((60*30)) && gnome-session-quit --power-off` for example).

But since you asked for this feature, I now have one idea. I want to add possibility to create a list of commands that will be stored, and a user can then select the needed one with a few clicks. Such feature, while being advanced, resolves the second issue I mentioned, it doesn't make an app just a "command-line where you don't type `sleep`".

Please let me know what do you think, any suggestions are welcome. I will start to investigate how to run commands outside of flatpak sandbox :)

**Comment by fsobolev** [comment]
It's implemented now. You can try it by building the app, a new release will be published on flathub after updating all translations. ☺️
